# Generated by Django 5.2.17 on 2026-08-16 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("logs", "0003_alter_pluslog_cycle_alter_pluslog_user"),
        ("quest", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "char_type",
                    models.CharField(
                        choices=[("CAT", "고양이"), ("DOG", "강아지")],
                        default="CAT",
                        max_length=10,
                    ),
                ),
                ("total_score", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "character_state",
            },
        ),
        migrations.CreateModel(
            name="CharacterGrowthEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("LOG", "플러스 로그"), ("QUEST", "퀘스트")],
                        max_length=10,
                    ),
                ),
                ("score", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logs.pluslog",
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quest.quest",
                    ),
                ),
                (
                    "char_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="growth_events",
                        to="characters.characterstate",
                    ),
                ),
            ],
            options={
                "db_table": "character_growth_event",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source_type", "LOG"),
                                ("log__isnull", False),
                                ("quest__isnull", True),
                            ),
                            models.Q(
                                ("source_type", "QUEST"),
                                ("quest__isnull", False),
                                ("log__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="char_growth_event_exclusive_fk",
                    )
                ],
            },
        ),
    ]
