# Generated by Django 5.2.17 on 2026-08-20 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "char_type",
                    models.CharField(
                        choices=[("CAT", "고양이"), ("DOG", "강아지")], max_length=10
                    ),
                ),
                ("character_name", models.CharField(max_length=10)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archived_characters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "character_archive",
                "ordering": ["-completed_at"],
            },
        ),
    ]
