# Generated by Django 5.2.17 on 2026-08-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_characterarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterarchive',
            name='char_type',
            field=models.CharField(choices=[('cat', '고양이'), ('dog', '강아지')], max_length=10),
        ),
        migrations.AlterField(
            model_name='characterstate',
            name='char_type',
            field=models.CharField(choices=[('cat', '고양이'), ('dog', '강아지')], default='cat', max_length=10),
        ),
    ]
