# Generated by Django 5.2.17 on 2026-08-10 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ACTIVE', '진행중'), ('RESTING', '휴식'), ('CLOSED', '종료')], db_column='State', max_length=7)),
                ('analysis', models.TextField(blank=True, db_column='Analysis', null=True)),
                ('user', models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사이클',
                'verbose_name_plural': '사이클 목록',
                'db_table': 'cycle',
            },
        ),
    ]
