# Generated by Django 5.2.17 on 2026-08-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_placeholder', models.IntegerField(db_column='User_ID', help_text='임시 필드. User 모델 생성 후 user FK로 교체 예정')),
                ('state', models.CharField(choices=[('ACTIVE', '진행중'), ('RESTING', '휴식'), ('CLOSED', '종료')], db_column='State', max_length=7)),
                ('analysis', models.TextField(blank=True, db_column='Analysis', null=True)),
                ('count', models.PositiveSmallIntegerField(db_column='Count')),
                ('last_updated_at', models.DateField(blank=True, db_column='Last_Updated_At', null=True)),
                ('closed_at', models.DateField(blank=True, db_column='Closed_At', null=True)),
                ('rest_started_at', models.DateField(blank=True, db_column='Rest_Started_At', null=True)),
                ('notified_at', models.DateField(blank=True, db_column='Notified_At', null=True)),
                ('started_at', models.DateField(db_column='Started_At')),
                ('analysis_request_count', models.PositiveSmallIntegerField(db_column='Analysis_Request_Count', default=0)),
            ],
            options={
                'verbose_name': '사이클',
                'verbose_name_plural': '사이클 목록',
                'db_table': 'cycle',
                'constraints': [models.CheckConstraint(condition=models.Q(('analysis_request_count__gte', 0), ('analysis_request_count__lte', 3)), name='cycle_analysis_request_count_between_0_and_3')],
            },
        ),
    ]
