# Generated by Django 5.2.17 on 2026-08-14 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ACTIVE', '진행중'), ('RESTING', '휴식'), ('CLOSED', '종료')], max_length=7)),
                ('analysis', models.JSONField(blank=True, null=True)),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('last_updated_at', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('rest_started_at', models.DateField(blank=True, null=True)),
                ('notified_at', models.DateField(blank=True, null=True)),
                ('started_at', models.DateField()),
                ('analysis_request_count', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사이클',
                'verbose_name_plural': '사이클 목록',
                'db_table': 'cycle',
                'ordering': ['-started_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('analysis_request_count__gte', 0), ('analysis_request_count__lte', 3)), name='cycle_analysis_request_count_between_0_and_3')],
            },
        ),
    ]
