# Generated by Django 5.2.17 on 2026-08-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='analysis',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='analysis_request_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='closed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='count',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='last_updated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='notified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='rest_started_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='started_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='state',
            field=models.CharField(choices=[('ACTIVE', '진행중'), ('RESTING', '휴식'), ('CLOSED', '종료')], max_length=7),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='user_id_placeholder',
            field=models.IntegerField(help_text='임시 필드. User 모델 생성 후 user FK로 교체 예정'),
        ),
    ]
