# Generated by Django 5.2.17 on 2026-08-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='character_id',
        ),
        migrations.AddField(
            model_name='user',
            name='character_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='character_type',
            field=models.CharField(blank=True, choices=[('cat', '고양이'), ('dog', '강아지')], max_length=3, null=True),
        ),
    ]
