# Generated by Django 5.2.17 on 2026-08-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_character_type_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('character_name', ''), ('character_type__isnull', True)), models.Q(('character_type__isnull', False), models.Q(('character_name', ''), _negated=True)), _connector='OR'), name='user_character_type_and_name_together'),
        ),
    ]
