# Generated by Django 5.2.17 on 2026-08-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='character_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
