# Generated by Django 5.2.17 on 2026-08-16 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_character_type_and_name_constraint'),
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cycle.cycle'),
        ),
    ]
