# Generated by Django 5.2.17 on 2026-08-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification_enabled',
        ),
        migrations.AddField(
            model_name='user',
            name='activity_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='restart_notification',
            field=models.BooleanField(default=True),
        ),
    ]
