# Generated by Django 5.2.17 on 2026-08-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_notification_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.CharField(max_length=500),
        ),
    ]
