# Generated by Django 5.2.17 on 2026-08-14 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('plus_log_count', models.PositiveSmallIntegerField(default=0)),
                ('success_quest_count', models.PositiveSmallIntegerField(default=0)),
                ('active_days', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rest_NT_content', models.CharField(blank=True, help_text='휴식기 알림 발송 문구', max_length=200)),
                ('analysis', models.JSONField(blank=True, default=dict, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_analysis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '위클리 분석',
                'verbose_name_plural': '위클리 분석 목록',
                'db_table': 'weekly_analysis',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_content', models.CharField(max_length=200)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('weekly_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='weekly_card.weeklyanalysis')),
            ],
            options={
                'verbose_name': '추천 퀘스트',
                'verbose_name_plural': '추천 퀘스트 목록',
                'db_table': 'recommended_quest',
            },
        ),
        migrations.AddConstraint(
            model_name='weeklyanalysis',
            constraint=models.UniqueConstraint(fields=('user', 'week_start'), name='weekly_analysis_unique_user_week'),
        ),
    ]
