# Generated by Django 5.2.17 on 2026-08-12 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_placeholder', models.IntegerField(db_column='User_ID', help_text='임시 필드. User 모델 생성 후 user FK로 교체 예정')),
                ('week_start', models.DateField(db_column='Week_Start')),
                ('week_end', models.DateField(db_column='Week_End')),
                ('plus_log_count', models.PositiveSmallIntegerField(db_column='Plus_Log_Count', default=0)),
                ('success_quest_count', models.PositiveSmallIntegerField(db_column='Success_Quest_Count', default=0)),
                ('active_days', models.PositiveSmallIntegerField(db_column='Active_Days', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_At')),
            ],
            options={
                'verbose_name': '위클리 분석',
                'verbose_name_plural': '위클리 분석 목록',
                'db_table': 'weekly_analysis',
                'constraints': [models.UniqueConstraint(fields=('user_id_placeholder', 'week_start'), name='weekly_analysis_unique_user_week')],
            },
        ),
        migrations.CreateModel(
            name='RecommendedQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_content', models.CharField(db_column='Quest_Content', max_length=200)),
                ('reason', models.CharField(blank=True, db_column='Reason', max_length=200, null=True)),
                ('weekly_analysis', models.ForeignKey(db_column='Weekly_Analysis_ID', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='weekly_card.weeklyanalysis')),
            ],
            options={
                'verbose_name': '추천 퀘스트',
                'verbose_name_plural': '추천 퀘스트 목록',
                'db_table': 'recommended_quest',
            },
        ),
    ]
