# Generated by Django 5.2.17 on 2026-08-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyanalysis',
            name='analysis',
            field=models.TextField(blank=True, db_column='Analysis'),
        ),
        migrations.AddField(
            model_name='weeklyanalysis',
            name='rest_NT_content',
            field=models.CharField(blank=True, db_column='Rest_NT_Content', max_length=200),
        ),
        migrations.AlterField(
            model_name='recommendedquest',
            name='reason',
            field=models.CharField(blank=True, db_column='Reason', max_length=200),
        ),
    ]
