# Generated by Django 5.2.17 on 2026-08-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_card', '0002_weeklyanalysis_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyanalysis',
            name='analysis',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
