# Generated by Django 5.2.17 on 2026-08-12 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ACTIVE', '진행중'), ('DONE', '완료'), ('FAILED', '실패'), ('ABANDONED', '포기')], db_column='State', max_length=9)),
                ('quest_content', models.CharField(db_column='Quest_Content', max_length=200)),
                ('last_checked', models.DateField(blank=True, db_column='Lastchecked', null=True)),
                ('count', models.PositiveSmallIntegerField(db_column='Count', default=0)),
                ('started_at', models.DateField(db_column='Started_At')),
                ('cycle', models.ForeignKey(db_column='Cycle_ID', on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='cycle.cycle')),
            ],
            options={
                'verbose_name': '퀘스트',
                'verbose_name_plural': '퀘스트 목록',
                'db_table': 'quest',
                'constraints': [models.CheckConstraint(condition=models.Q(('count__gte', 0), ('count__lte', 3)), name='quest_count_between_0_and_3')],
            },
        ),
    ]
