# Generated by Django 5.2.17 on 2026-08-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='abandoned_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
