# Generated by Django 5.2.17 on 2026-08-15 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("asset_id", models.AutoField(primary_key=True, serialize=False)),
                ("asset_name", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "asset",
            },
        ),
        migrations.CreateModel(
            name="PlusLog",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("user", models.IntegerField()),
                ("content", models.CharField(max_length=200)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("cycle", models.IntegerField()),
                (
                    "assets",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logs.asset",
                    ),
                ),
            ],
            options={
                "db_table": "plus_log",
            },
        ),
    ]
