# Generated by Django 5.2.17 on 2026-08-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pluslog",
            old_name="assets",
            new_name="asset",
        ),
        migrations.RemoveField(
            model_name="pluslog",
            name="retry_count",
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
